export class PatientWorkHistoryModel {
  public PatientWorkHistoryID: number;
  public VisitID: number;
  public RecordedDate: Date;
  public RecordedBy: string;
  public EmployerName: string;
  public ContactPerson: string;
  public Email: string;
  public CellPhone: string;
  public PhoneNo: string;
  public AddressLine1: string;
  public AddressLine2: string;
  public Town: string;
  public City: string;
  public District: string;
  public State: string;
  public Country: string;
  public PIN: string;
  public WorkDateFrom: Date;
  public WorkDateTo: Date;
  public AdditionalNotes: string;
  /*public Createddate: Date;
  public CreatedBy: Date;
  public ModifiedDate: Date;
  public ModifiedBy: string*/
  public RecordedTime: string;
  public visitDateandTime: string;
  public recordedDuring: string;
}
