import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';
import { MatDialogRef } from '@angular/material/dialog';


@Component({
  selector: 'triage-assessment',
  templateUrl: 'triage-assessment.component.html'
})

export class TriageAssessmentComponent implements OnInit {

  triageAssessmentForm: FormGroup;

  constructor(public dialogRef: MatDialogRef<TriageAssessmentComponent>, private fb: FormBuilder) { }  

  ngOnInit() {
    this.triageAssessmentForm = this.fb.group({
      //Ears
      ExternalSize:[''],
      IsExternalSize:[''],
      ExternalShape:[''],
      IsExternalShape:[''],
      LeftLesions:[''],
      IsLeftLesions:[''],
      RightLesions:[''],
      IsRightLesions:[''],
      LeftTragusMobile:[''],
      LeftTragusTender: [''],      
      RightTragusMobile:[''],
      RightTragusTender :[''],
      LeftMeatusPatent:[''],
      LeftMeatusDischarge:[''],
      RightMeatusPatent: [''], 
      RightMeatusDischarge:[''],
      IsLeftCanalClear:[''],
      LeftCanalClear:[''],
      IsRightCanalClear:[''],
      RightCanalClear: [''],          
      IsLeftCerumen:[''],
      IsRightCerumen:[''],
      LeftSoftCerumen:[''],
      LeftColorCerumen:[''],
      RightSoftCerumen:[''],
      RightColorCerumen:[''],
      IsLeftGray:[''],
      LeftGray:[''],
      IsRightGray:[''],
      RightGray:[''],
      IsLeftTympanicLesions:[''],
      LeftTympanicLesions:[''],
      IsRightTympanicLesions:[''],
      RightTympanicLesions:[''],
      IsFollowsDirections:[''],
      FollowsDirections:[''],
      IsAnswersDirections:[''],
      AnswersDirections:[''],
      IsWhisper:[''],
      Whisper:[''],
      IsLeftRinne: [''],         
      IsRightRinne: [''],         
      IsWeber: [''],         
      Weber: [''],         
      MaintainsBalance: [''],
      //Nose
      IsMidline: [''],         
      Midline: [''],         
      IsDischarge: [''],         
      Discharge: [''],         
      IsLeftNaresPatent: [''],                  
      LeftNaresPatent: [''],                  
      IsRightNaresPatent: [''],                  
      RightNaresPatent: [''],                  
      IsLMucosaPink: [''],                  
      LMucosaPink: [''],                  
      IsLMucosaMoist: [''],                  
      LMucosaMoist: [''],                  
      IsLMucosaLesions: [''],                  
      LMucosaLesions: [''],                         
      IsRMucosaPink: [''],                                 
      RMucosaPink: [''],                         
      IsRMucosaMoist: [''],                         
      RMucosaMoist: [''],                         
      IsRMucosaLesions: [''],                         
      RMucosaLesions: [''],                         
      IsSeptumMidline: [''],                         
      SeptumMidline: [''],                         
      IsSeptumIntact: [''],                         
      SpetumIntact: [''],
      //Sinuses
      LeftFrontalTender: [''],                         
      RightFrontalTender: [''],                         
      LeftMaxillaryTender: [''],                         
      RightMaxillaryTender: [''],
      //Mouth
      IsLipsSymmetrical: [''],                         
      LipsSymmetrical: [''],                         
      IsLipsMoist: [''],                         
      LipsMoist: [''],                                
      IsLipsLesions: [''],                         
      LipsLesions: [''],                         
      TeethStatus1: [''],                         
      TeethStatus2: [''],                         
      IsTeethIntact: [''],                         
      TeethIntact: [''],                         
      IsTeethDentures: [''],                         
      TeethDentures: [''],                         
      IsTongueMobile: [''],                         
      TongueMobile: [''],                         
      IsTonguePink: [''],                         
      TonguePink: [''],                         
      IsTongueMoist: [''],                         
      TongueMoist: [''],     
      IsTonguePapillar: [''],     
      TonguePapillar: [''],     
      IsTongueDorsumSmooth: [''],     
      TongueDorsumSmooth: [''],     
      IsTongueLesions: [''],     
      TongueLesions: [''],     
      IsGumsPink: [''],         
      GumsPink: [''],     
      IsGumsSmooth: [''],                                
      GumsSmooth: [''],                                
      IsGumsLesions: [''],                                
      GumsLesions: [''],                                
      IsSalivaryGlandsWhartons: [''],                                
      SalivaryGlandsWhartons: [''],                                
      IsSalivaryGlandsPatent: [''],                                
      SalivaryGlandsPatent: [''],                                
      IsSalivaryGlandsInflammation: [''],                                
      SalivaryGlandsInflammation: [''],                                
      IsSalivaryGlandsStensens: [''],                                
      SalivaryGlandsStensens: [''],                             
      IsSalivaryGlandsPatent1: [''],                                
      SalivaryGlandsPatent1: [''],                                
      IsSalivaryGlandsInflammation1: [''],                                
      SalivaryGlandsInflammation1: [''],                                
      IsHardPlateIntact: [''],                                
      HardPlateIntact: [''],
      //Throat
      IsUvulaMidline: [''],                                
      UvulaMidline: [''],                                        
      IsUvulaRise: [''],                                
      UvulaRise: [''],                                
      IsSoftPalateIntact: [''],                                
      SoftPalateIntact: [''],                                
      IsSoftPalateRise: [''],                                
      SoftPalateRise: [''],                                
      IsTonsils: [''],                                
      IsInflammation: [''],                                
      Inflammation: [''],                                
      IsColor: [''],                                
      Color: [''],
      //ODOR
      IsODOR: ['']                              
    });
  }
  closeDialog(): void {
    this.dialogRef.close();
  }
}
